"""Initial migration

Revision ID: eb8c87b4cddc
Revises: 
Create Date: 2025-06-10 21:49:46.193798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8c87b4cddc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    op.alter_column('currency_rates', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    op.alter_column('currency_rates', 'nominal',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_currency_date'), table_name='currency_rates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_currency_date'), 'currency_rates', ['date'], unique=False)
    op.alter_column('currency_rates', 'nominal',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=0),
               existing_nullable=True)
    op.alter_column('currency_rates', 'rate',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_table_pkey'))
    )
    # ### end Alembic commands ###
